services:
  - type: web
    name: tu-nombre-de-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PORT
        value: 8050