services:
  - type: web
    name: dashboard-mortalidad
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:server --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"